import { Inter } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";

// theme provider
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Karin Sukchai Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="Light">
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
